### ISSUE TITLE
May this code be used in research work?

### ISSUE THREAD

**Issue by LianzheWang** [TinfoilHat0/Learning-to-Reweight-Examples-for-Robust-Deep-Learning-with-PyTorch-Higher#2]
Hi Tinfoi, 

I think this code is very well done, and it is definitely a clean and efficient PyTorch implementation of the sample reweighting algorithm.

My question is, may this code be reused for other people's research work? (Including modification and release in research papers.) I believe it will benefit the research community really much.

I am personally doing research related to sample reweighting right now, and I hope to refer to some parts of your code. I would be very grateful if you can permit this and properly cite your work.

Thank you very much for your work.

**Comment by Patrick-wlz** [comment]
Thanks!
