### ISSUE TITLE
how is this different from https://github.com/danieltan07/learning-to-reweight-examples/

### ISSUE THREAD

**Issue by sdafkldkfaj** [TinfoilHat0/Learning-to-Reweight-Examples-for-Robust-Deep-Learning-with-PyTorch-Higher#3]
Hi, thanks for this awesome work!  

I came across another implementation: https://github.com/danieltan07/learning-to-reweight-examples/, but your version seems so much cleaner.  I wonder if you may know the main difference between your version and theirs?  I have experience with DL models but have no experience implementing meta-learning stuff, so any information would be much appreciated, thanks!

**Comment by TinfoilHat0** [comment]
I leveraged Higher library by PyTorch which makes computing higher order gradients much easier, and thus, simplifies the implementation :)
